import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create demo user
  const user = await prisma.user.create({
    data: {
      email: 'demo@jobcrawl.no',
      passwordHash: '$2b$10$example_hashed_password', // In production, use actual bcrypt hash
      fullName: 'Demo User',
      profile: {
        create: {
          skills: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
          experience: 3,
          education: 'Bachelor in Computer Science',
          location: 'Oslo, Norway',
          bio: 'Passionate full-stack developer with experience in modern web technologies.',
        },
      },
    },
  });

  console.log('✅ Created demo user:', user.email);

  // Create sample job listings
  const jobs = [
    {
      title: 'Senior Full-Stack Developer',
      company: 'TechCorp AS',
      location: 'Oslo',
      url: 'https://finn.no/example-job-1',
      description: 'We are looking for a skilled full-stack developer to join our team.',
      requirements: ['JavaScript', 'React', 'Node.js', 'PostgreSQL'],
      source: 'finn.no',
      publishedDate: new Date(),
    },
    {
      title: 'Frontend Developer',
      company: 'StartupHub',
      location: 'Bergen',
      url: 'https://finn.no/example-job-2',
      description: 'Join us as a frontend developer to build amazing user experiences.',
      requirements: ['React', 'TypeScript', 'CSS', 'Responsive Design'],
      source: 'finn.no',
      publishedDate: new Date(),
    },
  ];

  const createdJobs = await Promise.all(
    jobs.map(job => prisma.jobListing.create({ data: job }))
  );

  console.log(`✅ Created ${createdJobs.length} sample job listings`);

  // Create sample application
  const application = await prisma.application.create({
    data: {
      userId: user.id,
      jobListingId: createdJobs[0].id,
      status: 'DRAFT',
      coverLetter: 'This is a sample cover letter generated by our AI system...',
    },
  });

  console.log('✅ Created sample application');

  console.log('🎉 Seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

